from .word_cnn_for_imdb_sentiment_classification import WordCNNForIMDBSentimentClassification
from .word_cnn_for_mr_sentiment_classification import WordCNNForMRSentimentClassification
from .word_cnn_for_yelp_sentiment_classification import WordCNNForYelpSentimentClassification