name: Build documentation with Sphinx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pandoc -o Acquire::Retries=3
        python -m pip install --upgrade pip setuptools wheel
        python setup.py install_egg_info
        pip install -e .[docs]
        pip install jupyter ipykernel
    - name: Build docs with Sphinx and check for errors
      run: |
        sphinx-build -b html docs docs/_build/html
