from .alzantot_2018 import Alzantot2018
from .alzantot_2018_adjusted import Alzantot2018Adjusted
from .deepwordbug_gao_2018 import DeepWordBugGao2018
from .hotflip_ebrahimi_2017 import HotFlipEbrahimi2017
from .kuleshov_2017 import Kuleshov2017
from .seq2sick_cheng_2018_blackbox import Seq2SickCheng2018BlackBox
from .textfooler_jin_2019 import TextFoolerJin2019
from .textfooler_jin_2019_adjusted import TextFoolerJin2019Adjusted
from .mcts_recipe import MCTSRecipe
from .mcts_recipe_adjusted import MCTSRecipeAdjusted
from .mha_recipe import MHARecipe
from .mha_recipe_adjusted import MHARecipeAdjusted
from .beam_search_recipes import BeamSearch4WordEmbeddingStrong, BeamSearch8WordEmbeddingStrong
from .benchmark_recipes import *